spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.8.14:5432/test
        slave:
          username: postgres
          password: postgres
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://192.168.8.14:5432/test

