spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: 85ido
          password: 85ido@123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.104.96.20:3306/icip?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
        slave:
          username: 85ido
          password: 85ido@123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.104.96.20:3306/icip?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8


mybatis-plus:
  # 实体扫描路径
  type-aliases-package: orange.**.entity
  # xml文件扫描路径
  mapper-locations: classpath*:orange/**/dao/*.xml
  global-config:
    banner: false  # 禁止打印banner
    db-config:
    # 逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    useGeneratedKeys: true
    map-underscore-to-camel-case: true