spring:
  datasource:
    dynamic:
      datasource:
        master:
          username: 85ido
          password: 85ido@123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.104.96.20:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
        slave:
          username: 85ido
          password: 85ido@123
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://47.104.96.20:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
