server:
  port: 8080

spring:
  datasource:
    username: 85ido
    password: 85ido@123
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.104.96.20:3306/test?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT%2B8
flowable:
  idm:
    app:
      admin:
        user-id: admin
        password: test
        first-name: admin
        last-name: admin
  common:
    app:
      idm-url: http://localhost:8080
      idm-admin:
        user: admin
        password: test
  #关闭定时任务JOB
  async-executor-activate: false
  database-schema-update: true

