#spring:
#  data:
#    elasticsearch:
#      # elasticsearch集群名称，默认的是elasticsearch
#      cluster-name: elasticsearch
#      #节点的地址 注意api模式下端口号是9300，千万不要写成9200
#      cluster-nodes: 39.105.65.204:9300